name: 自动续期

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '45 1 * * *'

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 自动续期
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4

      - name: 运行时间
        run: |
          time=$(curl "http://quan.suning.com/getSysTime.do")
          echo -e ${time}

      - name: '自动续期'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          JM: ${{ secrets.JM }}
        run: python main.py
